name: Bug report
description: Is the integration crashing, or behaving incorrectly? Create a report to help us improve. Do not use for connectivity problems.
title: "[Bug]: "
labels: ["bug"]
body:

- type: markdown
  attributes:
    value: |

      > [!CAUTION]
      > Provide **all** the requested information. 
      >
      > Failing to do so will result in your bug report being closed as incomplete.


- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe your Huawei Solar Setup"
    description: "Please be thorough when describing your setup"
    value: |
      Inverter Type:
      Inverter Firmware version:
      sDongle present: Yes / No
      sDongle Type: sDongleA-05 (WiFi / Ethernet) / SDongleA-03 (4G)
      sDongle Connectivitiy: WiFi / Ethernet / 4G
      sDongle Firmware:
      Power meter present: three phase / single phase / no
      Optimizers Present: Yes / No
      Battery: LUNA2000-SO xxkWh / LUNA2000-S1 xxkWh (Released 2024) / LG RESU xxkWh / None
      Battery Firmware version:
      Huawei Solar integration version:
  validations:
    required: true

- type: dropdown
  id: connection_method
  attributes:
    label: How do you connect to the inverter?
    options:
      - Please select your connection method
      - Over serial, with a serial-to-USB stick
      - Over serial, with a serial-to-WiFi stick
      - Via the `SUN2000-<serial_no>` WiFi
      - Via the SDongle, wireless connection
      - Via the SDongle, wired connection
      - Via EMMA, wireless connection 
      - Via EMMA, wired connection 
      - Via SmartLogger 
  validations:
    required: true

- type: textarea
  attributes:
    label: "Upload your Diagnostics File"
    description: |
      ![Download diagnostics menu entry](https://raw.githubusercontent.com/wlcrs/huawei_solar/main/.github/ISSUE_TEMPLATE/images/download-diagnostics.png)
      1. Go to the 'Huawei Solar' integration settings page [![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=huawei-solar)
      2. Click on the three dots next to the integration entry
      3. Select 'Download diagnostis'
      4. Click on the textarea below, drag & drop the file into the textarea to upload it.
    value: Drag & Drop your Diagnostics File here.
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ## Relevant debug logs

      > [!IMPORTANT]
      > Just copy&pasting the error from the HA `System → Logs` page is insufficient in 95% of the cases.
      >
      > **You MUST gather debugging logs.**

      1. Enable debug logging
         ![Enable Debug Logging menu entry](https://raw.githubusercontent.com/wlcrs/huawei_solar/main/.github/ISSUE_TEMPLATE/images/enable-debug-logging.png)
      2. Reload the integration
      3. Perform the action that triggers the error (if applicable)
      4. Stop debug logging: a text file will be downloaded.

      Full instructions here: ['Debug Logs and Diagnostics' from the HA documentation](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics)

      If you are having problems during initial setup of this integration, you'll need to manually gather these logs. To do this, add the following lines to your `/config/configuration.yaml` and restart HA:

      ```yaml
      logger:
        default: debug
        logs:
          custom_components.huawei_solar: debug
          huawei_solar: debug
          tmodbus: debug # only include this if you're having connectivity issues
      ```

      Make sure to check for relevant log lines in the **Full logs** on the Logs settings page [![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/?)

      > [!IMPORTANT]
      > Do NOT copy&paste info from the summary that you see when going to `System → Logs`, always use "Show raw logs" and look there.
      > ![Raw logs](https://raw.githubusercontent.com/wlcrs/huawei_solar/main/.github/ISSUE_TEMPLATE/images/raw-logs.png)

- type: textarea
  attributes:
    label: Upload your relevant debug logs
    render: text
  validations:
    required: true

- type: checkboxes
  id: checks
  attributes:
    label: "Please confirm the following:"
    options:
      - label: I'm running the latest release of Home Assistant.
      - label: I'm running the latest release of this integration.
      - label: I did not find an existing issue describing this problem.
      - label: I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
      - label: I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)
      - label: I understand that skipping any of the above fields can result in my issue being closed as incomplete



