name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["feature", "triage"]
body:
- type: markdown
  attributes:
    value: |
      ### Scope of this integration
      
      This integration aims to expose the information and functions made available by Huawei Solar inverters directly **over Modbus** in Home Assistant.
      
      It does **NOT** do any interpretation of - or calculations with - this data. It does **NOT** interact with FusionSolar.

- type: textarea
  attributes:
    label: "Describe your feature request"
    placeholder: Please mention the relevant Modbus registers from the Huawei "Solar Inverter Modbus Interface Definitions" PDF in your request. 
  validations:
    required: true

- type: checkboxes
  id: no-bugreport
  attributes:
    label: "Proper usage"
    description: Please do not abuse this form to submit a problem that you are experiencing with this integration. The required fields in the 'Bug report' issue form are needed to understand your report. Your issue will be closed immediately without any reaction if you abuse this form.

    options:
      - label: I confirm that this is not a bug report
        required: true
      - label: I confirm that this feature request is within the stated scope of the integration
        required: true
